### ISSUE TITLE
Fontconfig error (cannot load default config file) on Fedora 30

### ISSUE THREAD

**Issue by europ** [snapcrafters/tmnationsforever#26] opened 2020-03-25 10:01 UTC
### Details

```
$ uname -i -s -r -v -m -o -p
Linux 5.5.9-100.fc30.x86_64 #1 SMP Thu Mar 12 14:15:32 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

$ lsb_release -a
LSB Version:    :core-4.1-amd64:core-4.1-noarch
Distributor ID: Fedora
Description:    Fedora release 30 (Thirty)
Release:        30
Codename:       Thirty

$ snap --version
snap    2.43.3-1.fc30
snapd   2.43.3-1.fc30
series  16
fedora  30
kernel  5.5.9-100.fc30.x86_64

$ snap info tmnationsforever
name:      tmnationsforever
summary:   TrackMania Nations Forever
publisher: Snapcrafters
store-url: https://snapcraft.io/tmnationsforever
contact:   https://github.com/snapcrafters/tmnationsforever/issues
license:   unset
description: |
  The most popular online PC racing game. It fuels 7 different racing environments; hundreds of
  thousands of tracks and millions of players to compete with. You can download the car you are
  dreaming of, paint it, drive it through insane tracks made of loops, ramps and off roads. It is
  all about you, your driving skills and the track in front of you.

  Just to make sure we understand each other: this is pure arcade driving madness.

  This snap is maintained by the Snapcrafters community and is not necessarily endorsed or
  officially maintained by the upstream developers.
commands:
  - tmnationsforever.launcher
  - tmnationsforever
  - tmnationsforever.wineboot
  - tmnationsforever.winecfg
  - tmnationsforever.winetricks
snap-id:      SMmdWwqPVDscid2Ragxl3kLgGwfbTN5h
tracking:     latest/stable
refresh-date: today at 10:23 CET
channels:
  stable:    2.11.26 2019-08-06 (32) 137MB -
  candidate: ↑
  beta:      ↑
  edge:      2.11.26 2019-12-03 (38) 137MB -
installed:   2.11.26            (32) 137MB -

$ tmnationsforever
Gtk-Message: Failed to load module "canberra-gtk-module"
Gtk-Message: Failed to load module "pk-gtk-module"
Gtk-Message: Failed to load module "canberra-gtk-module"
Gtk-Message: Failed to load module "pk-gtk-module"
Fontconfig warning: line 5: unknown element "its:rules"
Fontconfig warning: line 6: unknown element "its:translateRule"
Fontconfig error: line 6: invalid attribute 'translate'
Fontconfig error: line 6: invalid attribute 'selector'
Fontconfig error: line 7: invalid attribute 'xmlns:its'
Fontconfig error: line 7: invalid attribute 'version'
Fontconfig warning: line 9: unknown element "description"
Fontconfig error: Cannot load default config file
```

**Comment by stefan2904** [comment] 2020-03-27 12:26
I also get that on my up to date Ubuntu. It seems this is related to #8.

**Comment by galgalesh** [comment] 2021-09-18 21:00
Sounds indeed like a duplicate of #8, which should be fixed in the latest version.

**Closed by galgalesh** 2021-09-18 21:00 UTC
