### ISSUE TITLE
wine: Bad EXE format for Z:\tmp\tmnationsforever_setup.exe.

### ISSUE THREAD

**Issue by Jackaroo05** [snapcrafters/tmnationsforever#31] opened 2020-09-10 15:12 UTC
Hello. I am running Debian 10.5 on ChromeOS (Chromebook). I have tried installing tmnationsforevevr many times but it keeps failing to launch the installer due to "wine: Bad EXE format for Z:\tmp\tmnationsforever_setup.exe." I have tried the way it says to install it on the snap store (website, not the actual app because the app wont work) This is what I get when trying to install and run it:

```
jackaroo@penguin: ~$ sudo snap install tmnationsforever --edge

Fetch and check assertions for snap "tmnationsforever" (39)                                                                                                                /
Fetch and check assertions for snap "tmnationsforever" (39)                                                                                                                -
Fetch and check assertions for snap "tmnationsforever" (39)                                                                                                                \
Fetch and check assertions for snap "tmnationsforever" (39)                                                                                                                |
Fetch and check assertions for snap "tmnationsforever" (39)                                                                                                                /
Fetch and check assertions for snap "tmnationsforever" (39)                                                                                                                -
Fetch and check assertions for snap "tmnationsforever" (39)                                                                                                                \
Fetch and check assertions for snap "tmnationsforever" (39)                                                                                                                |
Fetch and check assertions for snap "tmnationsforever" (39)                                                                                                                /
Fetch and check assertions for snap "tmnationsforever" (39)                                                                                                                -
Fetch and check assertions for snap "tmnationsforever" (39)                                                                                                                \
Fetch and check assertions for snap "tmnationsforever" (39)                                                                                                                |
Fetch and check assertions for snap "tmnationsforever" (39)                                                                                                                /
Fetch and check assertions for snap "tmnationsforever" (39)                                                                                                                -
Fetch and check assertions for snap "tmnationsforever" (39)                                                                                                                \
Fetch and check assertions for snap "tmnationsforever" (39)                                                                                                                |
Fetch and check assertions for snap "tmnationsforever" (39)                                                                                                                /
Fetch and check assertions for snap "tmnationsforever" (39)                                                                                                                -
Mount snap "tmnationsforever" (39)                                                                                                                                         \
Mount snap "tmnationsforever" (39)                                                                                                                                         |
Mount snap "tmnationsforever" (39)                                                                                                                                         /
Mount snap "tmnationsforever" (39)                                                                                                                                         -
Mount snap "tmnationsforever" (39)                                                                                                                                         \
Mount snap "tmnationsforever" (39)                                                                                                                                         |
Mount snap "tmnationsforever" (39)                                                                                                                                         /
Mount snap "tmnationsforever" (39)                                                                                                                                         -
Mount snap "tmnationsforever" (39)                                                                                                                                         \
Mount snap "tmnationsforever" (39)                                                                                                                                         |
Mount snap "tmnationsforever" (39)                                                                                                                                         /
Mount snap "tmnationsforever" (39)                                                                                                                                         -
Mount snap "tmnationsforever" (39)                                                                                                                                         \
Mount snap "tmnationsforever" (39)                                                                                                                                         |
Mount snap "tmnationsforever" (39)                                                                                                                                         /
Mount snap "tmnationsforever" (39)                                                                                                                                         -
Mount snap "tmnationsforever" (39)                                                                                                                                         \
Copy snap "tmnationsforever" data                                                                                                                                          |
Setup snap "tmnationsforever" (39) security profiles                                                                                                                       /
Setup snap "tmnationsforever" (39) security profiles                                                                                                                       -
Setup snap "tmnationsforever" (39) security profiles                                                                                                                       \
Setup snap "tmnationsforever" (39) security profiles                                                                                                                       |
Setup snap "tmnationsforever" (39) security profiles                                                                                                                       /
Setup snap "tmnationsforever" (39) security profiles                                                                                                                       -
Setup snap "tmnationsforever" (39) security profiles                                                                                                                       \
Setup snap "tmnationsforever" (39) security profiles                                                                                                                       |
Automatically connect eligible plugs and slots of snap "tmnationsforever"                                                                                                  /
Connect tmnationsforever:joystick to core:joystick                                                                                                                         -
Setup snap "tmnationsforever" (39) security profiles for auto-connections                                                                                                  \
Setup snap "tmnationsforever" (39) security profiles for auto-connections                                                                                                  |
Setup snap "tmnationsforever" (39) security profiles for auto-connections                                                                                                  /
Setup snap "tmnationsforever" (39) security profiles for auto-connections                                                                                                  -
Setup snap "tmnationsforever" (39) security profiles for auto-connections                                                                                                  \
Setup snap "tmnationsforever" (39) security profiles for auto-connections                                                                                                  |
Setup snap "tmnationsforever" (39) security profiles for auto-connections                                                                                                  /
Setup snap "tmnationsforever" (39) security profiles for auto-connections                                                                                                  -
Setup snap "tmnationsforever" (39) security profiles for auto-connections                                                                                                  \
Setup snap "tmnationsforever" (39) security profiles for auto-connections                                                                                                  |
Setup snap "tmnationsforever" (39) security profiles for auto-connections                                                                                                  /
Run configure hook of "tmnationsforever" snap if present                                                                                                                   -
Run health check of "tmnationsforever" snap                                                                                                                                \
[0m[?25h[K[1mWarning:[0m /snap/bin was not found in your $PATH. If you've not restarted your session since you
         installed snapd, try doing that. Please see https://forum.snapcraft.io/t/9469 for more
         details.

tmnationsforever (edge) 2.11.26 from Snapcrafters installed
jackaroo@penguin: ~$ sudo snap connect tmnationsforever:joystick

jackaroo@penguin: ~$ sudo snap run tmnnationsforever
No protocol specified
Failed to connect to Mir: Failed to connect to server socket: No such file or directory
Unable to init server: Could not connect: Connection refused

(yad:5125): Gtk-WARNING **: cannot open display: :0
Fontconfig warning: line 5: unknown element "its:rules"
Fontconfig warning: line 6: unknown element "its:translateRule"
Fontconfig error: line 6: invalid attribute 'translate'
Fontconfig error: line 6: invalid attribute 'selector'
Fontconfig error: line 7: invalid attribute 'xmlns:its'
Fontconfig error: line 7: invalid attribute 'version'
Fontconfig warning: line 9: unknown element "description"
Fontconfig error: Cannot load default config file
Fontconfig warning: line 5: unknown element "its:rules"
Fontconfig warning: line 6: unknown element "its:translateRule"
Fontconfig error: line 6: invalid attribute 'translate'
Fontconfig error: line 6: invalid attribute 'selector'
Fontconfig error: line 7: invalid attribute 'xmlns:its'
Fontconfig error: line 7: invalid attribute 'version'
Fontconfig warning: line 9: unknown element "description"
Fontconfig error: Cannot load default config file
Fontconfig warning: line 5: unknown element "its:rules"
Fontconfig warning: line 6: unknown element "its:translateRule"
Fontconfig error: line 6: invalid attribute 'translate'
Fontconfig error: line 6: invalid attribute 'selector'
Fontconfig error: line 7: invalid attribute 'xmlns:its'
Fontconfig error: line 7: invalid attribute 'version'
Fontconfig warning: line 9: unknown element "description"
Fontconfig error: Cannot load default config file
No protocol specified
Fontconfig warning: line 5: unknown element "its:rules"
Fontconfig warning: line 6: unknown element "its:translateRule"
Fontconfig error: line 6: invalid attribute 'translate'
Fontconfig error: line 6: invalid attribute 'selector'
Fontconfig error: line 7: invalid attribute 'xmlns:its'
Fontconfig error: line 7: invalid attribute 'version'
Fontconfig warning: line 9: unknown element "description"
Fontconfig error: Cannot load default config file
0009:err:module:map_image Could not map section .rdata, file probably truncated
0029:err:module:map_image Could not map section .rdata, file probably truncated
wine: Bad EXE format for Z:\tmp\tmnationsforever_setup.exe.

removed '/tmp/tmnationsforever_setup.exe'
/snap/tmnationsforever/39/bin/sommelier: line 40: cd: /root/snap/tmnationsforever/common/.wine/drive_c/Program Files/TmNationsForever: No such file or directory
wine: cannot find '/root/snap/tmnationsforever/common/.wine/drive_c/Program Files/TmNationsForever/TmForever.exe'
jackaroo@penguin: ~$:

```
Wine is installed, I did sudo everything, and nothing works.

Any help is appreciated. Thanks!

**Comment by popey** [comment] 2020-11-03 15:36
Thanks for the issue report, sorry it took so long to respond. Looks like you've got an i386 install of Debian on your chromebook. I don't think we've ever tested tmnations on i386 based installs, so I am going to close the i386 channels and prevent it building until someone can confirm it works on i386 systems.

**Comment by seffs** [comment] 2020-12-04 17:22
Hi @popey , I wanted to confirm that it *works* in i386 systems. Instead of defining `- build: i386` I replaced it with `run on: [amd64,i386]` as it was a couple of months ago. You can test it in your machine. Idk if that makes any difference whatsoever

@Jackaroo05 you might have a bad installation of snap. Try reinstalling. Other than that, the Bad EXE format error also appears when there is a problem with the downloaded installer. As of now I have confirmed the following scenarios:
*Internet shutdown while downloading installer
*No space left on device
Try to solve that if that's the case

**Comment by seffs** [comment] 2020-12-04 22:38
So I tried building using a i386 system (Debian 10.6) and it also worked...except I had to use lxd instead of normal mode. So the problem is not the architecture but might be either a connection, space or bad installation issue.

**Comment by galgalesh** [comment] 2021-09-18 20:51
We don't support a i386 version anymore, so closing this.

**Closed by galgalesh** 2021-09-18 20:51 UTC
