### ISSUE TITLE
So this snap is officially broken and never to be fixed?

### ISSUE THREAD

**Issue by isthereanamenotalreadytaken** [snapcrafters/tmnationsforever#22] opened 2019-06-01 02:30 UTC
Same problem as everyone else. Been patiently waiting to see if it would ever be fixed. I guess not. I don't need snap for any other reason so I guess its uninstall time. Sad, this was awesome while it lasted. 

Oh and for the record ...

snap run tmnationsforever
/snap/tmnationsforever/28/bin/sommelier: line 222: 17889 Segmentation fault      env WINEARCH="${WINEARCH}" WINEPREFIX="${WINEPREFIX}" "${WINELOADER}" wineboot --init 2>&1
     17890                       | yad --progress --title="Preparing Windows environment" --width=400 --center --no-buttons --auto-close --auto-kill --on-top --pulsate
/snap/tmnationsforever/28/bin/sommelier: line 223: 17888 Segmentation fault      yad --timeout=15 --timeout-indicator=bottom --text="${NOTICE}" --no-escape --width=460 --center --no-buttons --splash --on-top
/snap/tmnationsforever/28/bin/sommelier: line 10: 17891 Segmentation fault      wget "${INSTALL_URL}" -O "${TMPDIR}/${INSTALL_EXE}" 2>&1
     17892                       | perl -p -e '$| = 1; s/^.* +([0-9]+%) +([0-9,.]+[GMKB]) +([0-9hms,.]+).*$/\1\n# Downloading... \2 (\3)/'
     17893                       | yad --progress --title="${INSTALL_EXE}" --width=400 --center --no-buttons --auto-close --auto-kill --on-top --no-escape
/snap/tmnationsforever/28/bin/sommelier: line 10: 17894 Segmentation fault      env WINEARCH="${WINEARCH}" WINEPREFIX="${WINEPREFIX}" "${WINELOADER}" "${TMPDIR}/${INSTALL_EXE}" /silent
rm: cannot remove '/tmp/tmnationsforever_setup.exe': No such file or directory
/snap/tmnationsforever/28/bin/sommelier: line 40: cd: /home/burginthorn/snap/tmnationsforever/common/.wine/drive_c/Program Files/TmNationsForever: No such file or directory
/snap/tmnationsforever/28/bin/sommelier: line 34: 17898 Segmentation fault      env WINEARCH="${WINEARCH}" WINEPREFIX="${WINEPREFIX}" "${WINELOADER}" "${WINE_EXE}"

Just like everyone else who can't play anymore ...

**Comment by Whytey** [comment] 2019-07-22 12:41
Tried this last week and had the same issue.  Tried today and it seems to be corrected.  Just played a game.

djwhyte@david-7378:~$ !844
snap info tmnationsforever 
name:      tmnationsforever
summary:   TrackMania Nations Forever
publisher: Snapcrafters
contact:   https://github.com/snapcrafters/tmnationsforever/issues
license:   unset
description: |
  The most popular online PC racing game. It fuels 7 different racing environments; hundreds of
  thousands of tracks and millions of players to compete with. You can download the car you are
  dreaming of, paint it, drive it through insane tracks made of loops, ramps and off roads. It is
  all about you, your driving skills and the track in front of you.
  
  Just to make sure we understand each other: this is pure arcade driving madness.
  
  This snap is maintained by the Snapcrafters community and is not necessarily endorsed or
  officially maintained by the upstream developers.
commands:
  - tmnationsforever.launcher
  - tmnationsforever
  - tmnationsforever.wineboot
  - tmnationsforever.winecfg
  - tmnationsforever.winetricks
snap-id:      SMmdWwqPVDscid2Ragxl3kLgGwfbTN5h
tracking:     edge
refresh-date: 11 days ago, at 22:01 AEST
channels:
  stable:    2.11.26 2019-01-23 (28) 131MB -
  candidate: ↑                             
  beta:      ↑                             
  edge:      2.11.26 2019-06-20 (30) 131MB -
installed:   2.11.26            (30) 131MB -

**Comment by Caleb642** [comment] 2019-07-24 11:06
sadly having an issue starting that seems the same as above

`/snap/tmnationsforever/28/bin/sommelier: line 222:  9577 Segmentation fault      (core dumped) yad --timeout=15 --timeout-indicator=bottom --text="${NOTICE}" --no-escape --width=460 --center --no-buttons --splash --on-top
/snap/tmnationsforever/28/bin/sommelier: line 222:  9578 Segmentation fault      (core dumped) env WINEARCH="${WINEARCH}" WINEPREFIX="${WINEPREFIX}" "${WINELOADER}" wineboot --init 2>&1
      9579                       (core dumped) | yad --progress --title="Preparing Windows environment" --width=400 --center --no-buttons --auto-close --auto-kill --on-top --pulsate
/snap/tmnationsforever/28/bin/sommelier: line 10:  9583 Segmentation fault      (core dumped) wget "${INSTALL_URL}" -O "${TMPDIR}/${INSTALL_EXE}" 2>&1
      9584                       (core dumped) | perl -p -e '$| = 1; s/^.* +([0-9]+%) +([0-9,.]+[GMKB]) +([0-9hms,.]+).*$/\1\n# Downloading... \2 (\3)/'
      9585                       (core dumped) | yad --progress --title="${INSTALL_EXE}" --width=400 --center --no-buttons --auto-close --auto-kill --on-top --no-escape
/snap/tmnationsforever/28/bin/sommelier: line 10:  9589 Segmentation fault      (core dumped) env WINEARCH="${WINEARCH}" WINEPREFIX="${WINEPREFIX}" "${WINELOADER}" "${TMPDIR}/${INSTALL_EXE}" /silent
rm: cannot remove '/tmp/tmnationsforever_setup.exe': No such file or directory
/snap/tmnationsforever/28/bin/sommelier: line 40: cd: /home/caleb642/snap/tmnationsforever/common/.wine/drive_c/Program Files/TmNationsForever: No such file or directory
/snap/tmnationsforever/28/bin/sommelier: line 34:  9600 Segmentation fault      (core dumped) env WINEARCH="${WINEARCH}" WINEPREFIX="${WINEPREFIX}" "${WINELOADER}" explorer /desktop="virtual","${NATIVE_RES}" "${WINE_EXE}"
`

**Comment by Whytey** [comment] 2019-07-24 11:20
Follow the edge channel and see if that helps, they are up to version 30.

**Comment by popey** [comment] 2019-08-06 12:40
Duplicate of #21

**Closed by popey** 2019-08-06 12:40 UTC
