### ISSUE TITLE
fontconfig and driver issues using arch

### ISSUE THREAD

**Issue by rehtlaw** [snapcrafters/tmnationsforever#14] opened 2018-07-01 11:08 UTC
when running the snap, I get this output (on arch linux)
https://hastebin.com/ovizituhir.sql

**Comment by xordspar0** [comment] 2020-10-30 15:07
That link is dead, but it sounds like a duplicate of #8.

**Comment by galgalesh** [comment] 2021-09-18 20:59
Sounds indeed like a duplicate of #8

**Closed by galgalesh** 2021-09-18 20:59 UTC
