### ISSUE TITLE
Crash on start - snap  2.11.26

### ISSUE THREAD

**Issue by versus167** [snapcrafters/tmnationsforever#20] opened 2019-03-19 05:42 UTC
tmnationsforever does not start:

ERROR: ld.so: object 'libgtk3-nocsd.so.0' from LD_PRELOAD cannot be preloaded (failed to map segment from shared object): ignored.
/snap/tmnationsforever/28/bin/sommelier: line 197:  1156 Segmentation fault      (core dumped) $SNAP/usr/lib/$ARCH/gdk-pixbuf-2.0/gdk-pixbuf-query-loaders > $GDK_PIXBUF_MODULE_FILE
/snap/tmnationsforever/28/bin/sommelier: line 222:  1159 Segmentation fault      (core dumped) env WINEARCH="${WINEARCH}" WINEPREFIX="${WINEPREFIX}" "${WINELOADER}" wineboot --init 2>&1
      1160                       (core dumped) | yad --progress --title="Preparing Windows environment" --width=400 --center --no-buttons --auto-close --auto-kill --on-top --pulsate
/snap/tmnationsforever/28/bin/sommelier: line 222:  1158 Segmentation fault      (core dumped) yad --timeout=15 --timeout-indicator=bottom --text="${NOTICE}" --no-escape --width=460 --center --no-buttons --splash --on-top
/snap/tmnationsforever/28/bin/sommelier: line 10:  1221 Segmentation fault      (core dumped) wget "${INSTALL_URL}" -O "${TMPDIR}/${INSTALL_EXE}" 2>&1
      1222                       (core dumped) | perl -p -e '$| = 1; s/^.* +([0-9]+%) +([0-9,.]+[GMKB]) +([0-9hms,.]+).*$/\1\n# Downloading... \2 (\3)/'
      1224                       (core dumped) | yad --progress --title="${INSTALL_EXE}" --width=400 --center --no-buttons --auto-close --auto-kill --on-top --no-escape
/snap/tmnationsforever/28/bin/sommelier: line 10:  1233 Segmentation fault      (core dumped) env WINEARCH="${WINEARCH}" WINEPREFIX="${WINEPREFIX}" "${WINELOADER}" "${TMPDIR}/${INSTALL_EXE}" /silent
rm: cannot remove '/tmp/tmnationsforever_setup.exe': No such file or directory
/snap/tmnationsforever/28/bin/sommelier: line 40: cd: /home/volker/snap/tmnationsforever/common/.wine/drive_c/Program Files/TmNationsForever: No such file or directory
/snap/tmnationsforever/28/bin/sommelier: line 34:  1247 Segmentation fault      (core dumped) env WINEARCH="${WINEARCH}" WINEPREFIX="${WINEPREFIX}" "${WINELOADER}" explorer /desktop="virtual","${NATIVE_RES}" "${WINE_EXE}"

It was running before - some months ago, but now... Any idea?

**Comment by WuerfelDev** [comment] 2019-03-19 09:22
I tried to install it today, and run into the same problem too. Got the exact same error message.

I managed to install it by running winetricks, then select to install a game, choose tmnationsforever. After leaving everything by default I got it installed and it worked :)

**Comment by BrancolinoX** [comment] 2019-03-21 16:57
Im getting these errors too on opensuse leap. Unable to run tmnationsforever at the moment. Looks like an issue with wine.

**Comment by scureza** [comment] 2019-03-23 11:43
Same for me on Arch Linux.

**Comment by BrancolinoX** [comment] 2019-03-24 12:53
It was the only snap I used. I believe it may be a while before it even gets noticed. The guys seem very busy. Oh well, it was good while it lasted. Is there any way we can revert it back to the working version? I cant seem to find any info on this.

**Comment by mmtrt** [comment] 2019-03-25 05:59
@BrancolinoX you can run command `snap revert snapname` **OR** `snap revert snapname --revision xx` to restore snap to previous revision.

That segfault issue is probably caused by `libc` update on `core16` snaps with wine, I also had encountered similar issue when my wine snaps were on `core16`. So to fix this issue either dev have to ship older `libc` version precisely `libc6_2.23-0ubuntu10` in the snap **OR** upgrade snap base from `core16` to `core18` inorder to fix that issue.

**Comment by BrancolinoX** [comment] 2019-03-27 17:47
It says there are no revisions. Reverted back to wine. It has its faults but not quite as bad as the snaps. Hopefully they will become more stable in time. Seems the testing process could do with improvements.

**Comment by dogmax** [comment] 2019-12-02 23:34
Still not fixed.

**Comment by galgalesh** [comment] 2021-09-18 20:47
This should be fixed in the latest version. Please reopen the issue if you still experience this issue.

**Closed by galgalesh** 2021-09-18 20:47 UTC
